### ISSUE TITLE
Error parsing Recipients

### ISSUE THREAD

**Issue by GPHofficial** [opsgenie/opsgenie-python-sdk#20]
Library's method  __deserialize from api_client.py is wrongfully parsing Recipient Class Objects into UserRecipient / TeamRecipients

Expected: {'type': 'user', 'id': '{UUID_HERE}'}
Actual: {'name': None}

Reproducing: Call list_alerts, and check the field of responders.

**Comment by GPHofficial** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/2845

**Comment by davidban77** [comment]
Currently facing this issue as well

**Comment by zfr** [comment]
Hi @GPHofficial and @davidban77 

Thanks for bringing the issue. I sent a fix about the current problem. It used another DTO (Recipient) instead of Responder, and it causes that case. In the meantime, @GPHofficial was also right about the inheritance problem at the openapi-generator. I tried to fix it temporarily by removing the inheritance props.

When I have time, I'll try to pull the latest openapi-generator updates to our repo. Then we can re-enable inheritance again.

Thanks,
